export default {
    /*GAME_WIDTH: 720,
    GAME_HEIGHT: 1142,
    WORLD_BOUNDS_WIDTH: 720,
    WORLD_BOUNDS_HEIGHT: 1800,*/
    GAME_WIDTH: 720,
    GAME_HEIGHT: 1142,
    WORLD_BOUNDS_WIDTH: 720,
    WORLD_BOUNDS_HEIGHT: 1142,
    PREFIX_ASSET_URL: './../assets/',
    DEBUG_MODE: true,
}