export default {
    /*GAME_WIDTH: 720,
    GAME_HEIGHT: 1142,
    WORLD_BOUNDS_WIDTH: 720,
    WORLD_BOUNDS_HEIGHT: 1800,*/
    CAMERA_VIEW_WIDTH: 720,
    CAMERA_VIEW_HEIGHT: 1200,
    WORLD_BOUNDS_WIDTH: 720,
    WORLD_BOUNDS_HEIGHT: 3000,
    PREFIX_ASSET_URL: './../assets/',
    DEBUG_MODE: true,
}