const PREFIX_ASSET_URL =  './../assets/';

export default {
    /*GAME_WIDTH: 720,
    GAME_HEIGHT: 1142,
    WORLD_BOUNDS_WIDTH: 720,
    WORLD_BOUNDS_HEIGHT: 1800,*/
    GRAVITY: 0.4,
    DEBUG_MODE: true,
    CAMERA_VIEW_WIDTH: 720,
    CAMERA_VIEW_HEIGHT: 1142,
    WORLD_BOUNDS_WIDTH: 720,
    WORLD_BOUNDS_HEIGHT: 3000,
    GAME_STAGE_BACKGROUND_COLOR: '#1f1f1f',
    PREFIX_IMAGE_URL: PREFIX_ASSET_URL + 'image/',
    PREFIX_SOUND_URL: PREFIX_ASSET_URL + 'sound/',
    PREFIX_SPRITESHEET_URL: PREFIX_ASSET_URL + 'spritesheet/',
}